version: "3.9"

services:
  oracle:
    image: gvenzl/oracle-xe:18-slim
    # Forward Oracle port
    ports:
      - "1521:1521"
    environment:
      #This variable is mandatory for the first container startup and specifies the password for the Oracle Database SYS and SYSTEM users.
      ORACLE_PASSWORD: 123456
      #service name
      #ORACLE_DATABASE: XEPDB1
      APP_USER: useroracle
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-volume:/opt/oracle/oradata
    networks:
      - default

  jenkins:
    build:
      context: docker/jenkins
      dockerfile: Dockerfile
    hostname: appmodelo_jenkins
    ports:
      - "8089:8080"
      - "8888" # port used to communication with selenium grid
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - default



  firefox:
    image: selenium/node-firefox:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
      - default

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - default

#  dev:
#    build:
#      context: docker/dev
#      dockerfile: Dockerfile
#    hostname: dev
#    container_name: dev
#    user: spring
#    volumes:
#      - .:/AppModelo
#      - m2-repo:/spring/.m2
#      - gradle-cache:/spring/.gradle
#      - grails-cache:/spring/.grails
#    tty: true
#
#    ports:
#      - "8080:8080"
#    networks:
#      - default

volumes:
  oracle-volume:
  jenkins_home:
  m2-repo:
  gradle-cache:
  grails-cache:

networks:
  default:
    driver: bridge
