version: "3.9"

services:
  oracle:
    image: gvenzl/oracle-xe:18-slim
    # Forward Oracle port
    ports:
      - 1521:1521
    environment:
      #This variable is mandatory for the first container startup and specifies the password for the Oracle Database SYS and SYSTEM users.
      ORACLE_PASSWORD: 123456
      #service name
      #ORACLE_DATABASE: XEPDB1
      APP_USER: useroracle
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-volume:/opt/oracle/oradata
    networks:
      - default

  jenkins:
    #image: jenkins/jenkins:lts
    build:
      context: docker/jenkins
      dockerfile: Dockerfile
    #privileged: true
    #user: root
    ports:
      - 8089:8080
      #- 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - default

  selenium-hub:
    image: selenium/hub:3.141.59-20210607
    container_name: selenium-hub
    ports:
      - 4444:4444
    #volumes:
    #  - selenium-volume:/var/lib/selenium
    networks:
      - default

  chrome:
    image: selenium/node-chrome:3.141.59-20210607
    #volumes:
      #- /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - default

  firefox:
    image: selenium/node-firefox:3.141.59-20210607
    #volumes:
      #- /dev/shm/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - default




volumes:
  oracle-volume:
  jenkins_home:

networks:
  default:
    driver: bridge
