version: "3.9"

services:
  oracle:
    image: gvenzl/oracle-xe:18-slim
    # Forward Oracle port
    expose:
      - 1521
    environment:
      #This variable is mandatory for the first container startup and specifies the password for the Oracle Database SYS and SYSTEM users.
      ORACLE_PASSWORD: 123456
      #service name
      #ORACLE_DATABASE: XEPDB1
      APP_USER: useroracle
      APP_USER_PASSWORD: 123456
    volumes:
      - oracle-volume:/opt/oracle/oradata
    network_mode: host

  jenkins:
    #image: jenkins/jenkins:lts
    build:
      context: docker/jenkins
      dockerfile: Dockerfile
    #privileged: true
    #user: root
    expose:
      - 8089
      #- 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /usr/local/bin/docker:/usr/local/bin/docker
    network_mode: host

#
#  chrome:
#    image: selenium/node-chrome:4.1.1-20211217
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=127.0.0.1
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#    network_mode: host



  firefox:
    image: selenium/node-firefox:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=127.0.0.1
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    network_mode: host

  selenium-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-hub
    expose:
      - "4442"
      - "4443"
      - "4444"
    network_mode: host

  dev:
    build:
      context: docker/dev
      dockerfile: Dockerfile
    user: spring
    volumes:
      - .:/AppModelo
    tty: true
    expose:
      - "8080"
    network_mode: host

volumes:
  oracle-volume:
  jenkins_home:

